#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep  2 18:35:40 2021

@author: alberto

Escribir un programa que lea un entero positivo, n , introducido por el usuario y después muestre en pantalla la suma de todos los enteros desde 1 hasta . La suma de los primeros enteros positivos puede ser calculada de la siguiente forma:
"""


numero =int(input("Introduce un numero positivo para sacar su suma  de uno hast el n numeor  digitado: "))

suma= numero*(numero+1)/2

print("la suma de los primeros numeros enteros de 1 hasta "+ str(numero) + "es: " + str(suma))